theme: minima
title: Cairo's Blog
author: Cairo Sanders
email: cairosanders@hotmail.com
description: 4th year comp sci and psychology major at the university of victoria
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle cairosanders

show_excerpts: true # set to false to remove excerpts on the homepage
